version: '3'

services:
  # Service MySQL
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
      - MYSQL_USER=devops_user
      - MYSQL_PASSWORD=devops_password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # Monte le répertoire contenant tous les fichiers .sql
    networks:
      - devops-network

  # Service Backend (Spring Boot)
  projet-back:
    depends_on:
      - mysqldb
    image: molkadh/projet-back:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devops?useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: devops_user
      SPRING_DATASOURCE_PASSWORD: devops_password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    stdin_open: true
    tty: true
    networks:
      - devops-network

  # Service Frontend
  projet-front:
    depends_on:
      - projet-back
    image: molkadh/projet-front:1.0.0
    restart: on-failure
    ports:
      - 80:80
    networks:
      - devops-network

# Volumes pour la persistance des données MySQL
volumes:
  db:

# Réseau personnalisé pour connecter les services entre eux
networks:
  devops-network:
    driver: bridge
