version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=projetdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  projet-back:
    depends_on:
      - mysqldb
    build:
      context: ./Back  
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/projetdb?useSSL=false&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "rootpassword",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" }'
    stdin_open: true
    tty: true

  projet-front:
    build:
      context: ./Front  # Dossier contenant le Dockerfile du frontend
    restart: on-failure
    ports:
      - 80:80  
    depends_on:
      - projet-back  
    stdin_open: true
    tty: true

volumes:
  db:
