version: '3.8'

services:
  # Service MySQL (base de données)
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=projetdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  # Service Backend (Spring Boot)
  projet-back:
    depends_on:
      - mysqldb
    build:
      context: ./Back  # Dossier contenant le Dockerfile du backend
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/projetdb?useSSL=false&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "rootpassword",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" }'
    stdin_open: true
    tty: true

  # Service Frontend (Angular)
  projet-front:
    build:
      context: ./Front  # Dossier contenant le Dockerfile du frontend
    restart: on-failure
    ports:
      - 80:80  # Expose le port 80 (Nginx)
    depends_on:
      - projet-back  # Assurez-vous que le backend est prêt avant de démarrer le frontend
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local  # Volume pour MySQL
