vversion: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: docker-compose-mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Back
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql 
    

  projet-back:
    depends_on:
      - mysqldb
    image: molkadh/projet-back:1.0.0
    restart: on-failure
    ports:
      - "8082:8082"  # Si l'app back écoute sur 8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Back?useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
     

  projet-front:
    depends_on:
      - mysqldb
    image: molkadh/projet-front:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Back?useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db:
