version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root          # Mot de passe root
      - MYSQL_DATABASE=devops             # Base de données à créer
      - MYSQL_USER=devops_user            # Utilisateur de la base
      - MYSQL_PASSWORD=devops_password    # Mot de passe pour l'utilisateur
    ports:
      - 3306:3306                         # Mappage du port MySQL
    volumes:
      - db:/var/lib/mysql                 # Volume persistant pour MySQL
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monter le fichier SQL d'init

  projet-back:
    depends_on:
      - mysqldb
    build: molkadh/projet-front:1.0.0       # Image backend à construire
    restart: on-failure
    ports:
      - 8089:8089                           # Port d'exposition du backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devops?useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: devops_user
      SPRING_DATASOURCE_PASSWORD: devops_password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    stdin_open: true
    tty: true

  projet-front:
    depends_on:
      - mysqldb
    image: molkadh/projet-front:1.0.0       # Image frontend à utiliser
    restart: on-failure
    ports:
      - 80:80                               # Port d'exposition du frontend

volumes:
  db:                                      # Volume Docker pour persister les données MySQL
