services:
  mysql-db:
    image: mysql:latest
    container_name: docker-compose-mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Back
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql 

  projet-back:
    depends_on:
      - mysql-db
    image: molkadh/projet-back:1.0.0
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/Back?useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - my-network

  projet-front:
    depends_on:
      - mysql-db
    image: molkadh/projet-front:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/Back?useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
